### PR TITLE
MCOD algorithm + single phase and outlier clusterer support for it

### PR DESCRIPTION
**Pull request by dkrleza**
Additions in this pull request are:

1. **MCOD implementation**
A Java code that allows interface to the MOA MCOD implementation. I needed to overrride some methods from the MOA package, as the existing interface was not compatible with stream/streamMOA features and outlier detection additions. The introduced interface can be changed when or if the MOA MCOD implementation changes. I did not want to impose too hard dependency between MOA and streamMOA, which is the reason why the interface in the Java files is so "thick". **This MCOD implementation goes together with _stream_ additions.**
An example of the usage would be:
`
d <- DSD_Gaussians(k=10,d=2,o=10,lim=c(0,50),separation_type="Mahalanobis",outlier_horizon=10000,variance_lim=2,mahalanobis_separation=6)
mic_c <- DSC_MCOD(r=3.5,w=10000)
mac_c <- DSC_Kmeans(k=10,weighted=T)
c <- DSC_TwoStage(mic_c,mac_c)
evaluate(c,d,n=10000,type="macro",measure=c("cRand","OutlierJaccard"))
noutliers(c)
print(c)
reset_stream(d)
plot(c,d,n=10000,type="all")
`

### CODE REVIEW

**Comment by mhahsler** [comment]
Hi Dalibor, 

Thanks for your contribution. I get the following when I try to build/install the new package:

```
Error: package or namespace load failed for ‘streamMOA’:
 object 'get_outlier_positions' not found whilst loading namespace 'streamMOA'
Error: loading failed
```

Maybe a generic is needed?

**Comment by dkrleza** [comment]
Eh. I wasn't too clear about this. These _streamMOA_ contributions depend on _stream_ contributions that you got in the other pull request. So you need to build and install _stream_ first and then this.
`get_outlier_positions` is newly defined and exported in the _stream_ package, and here its only used for the MCOD clusterer implementation.

**Comment by mhahsler** [comment]
I forgot to update stream first. Now it works. The code changes look good. Please add the needed changes to the documentation and make sure that `R CMD check` runs clean. 

Thanks,
Michael

**Comment by dkrleza** [comment]
Ok. Stand by for it. Should not take too long.

**Comment by dkrleza** [comment]
Done. It is passing the CRAN checks now. Updated the version to 1.2-3.
Updated the vignette as well. Added my name to the DESCRIPTION file and related Rd files.

**Comment by mhahsler** [comment]
On CRAN now. Thanks for contributing code.

-m

**Pull request merged**
