### PR TITLE
Updated MOA library and added streamKM, BICO and Dstream interfaces

### PR DESCRIPTION
**Pull request by MatthiasCarnein**
Hi, I took the liberty and updated the package to the June 2018 release of the MOA library ([https://moa.cms.waikato.ac.nz/](https://moa.cms.waikato.ac.nz/)). I hope you don't mind!

I made all the necessary interface changes. In addition, this allows us to interface new MOA algorithms. In particular, I added interfaces to the streamKM, BICO and Dstream implementations. To my knowledge, we now have interfaces to all stream clustering algorithms in MOA. Since we already have implementations of BICO and Dstream in our main package, I did not export the functions to the namespace (but they are still available using the prefix streamMOA::: ).

The streamKM implementation only exports macro-clusters but not micro-clusters. In its current implementation, streamMOA would return the macro-clusters as micro-clusters and claim that macro-clusters are not available. I found that to be confusing and changed the behaviour in `DSC_MOA`. The package now returns micro-clusters if available and issues the usual error if not. The same applies for macro-clusters.

From my testing, everything seems to work fine:

```R
library(streamMOA)


# Existing DSD Interfaces

stream <- DSD_RandomRBFGeneratorEvents()
get_points(stream, 10, class=TRUE)
plot(stream)

# Existing DSC interfaces

stream = DSD_Gaussians(2,2)
algorithm = DSC_CluStream()
update(algorithm, stream, 1000)
get_centers(algorithm, "micro")
get_centers(algorithm, "macro")
plot(algorithm, stream, type="both")

algorithm = DSC_ClusTree()
update(algorithm, stream, 1000)
get_centers(algorithm, "micro")
plot(algorithm, stream, type="micro")

algorithm = DSC_DenStream()
update(algorithm, stream, 10000)
get_centers(algorithm, "micro")
get_centers(algorithm, "macro")
plot(algorithm, stream, type="both")


# New DSC interfaces

algorithm = DSC_streamkm(sizeCoreset = 1000, numClusters = 5)
update(algorithm, stream, 1000)
get_centers(algorithm, "macro")
plot(algorithm, stream, type="macro")

# The following two also work but are not exported to the namespace since we already have implementation in the stream Package
algorithm = streamMOA:::DSC_BICO(Cluster=5, Dimensions = 2, MaxClusterFeatures = 1000, Projections = 10)
update(algorithm, stream, 1000)
get_centers(algorithm, "micro")
get_centers(algorithm, "macro")
plot(algorithm, stream, type="both")

stream = DSD_Gaussians(2,2, mu=rbind(c(-100,-100), c(100,100)))
algorithm = streamMOA:::DSC_DStream()
update(algorithm, stream, 10000)
get_centers(algorithm, "macro")
plot(algorithm, stream, type="macro")
```

Let me know if you diasgree with any of the changes!

### CODE REVIEW

**Comment by MatthiasCarnein** [comment]
I think the CI fails because Magick++ is missing on the test-system. Let me know if it's related to my changes.

**Comment by mhahsler** [comment]
This is great! Thank you for putting in all the work. I think we should export the new algorithms. How about as DSC_BICO_MOA, etc. If you think that this is a good idea, then please add a man page for each algorithm and modify the pull request.

Happy New Year,
Michael

**Comment by MatthiasCarnein** [comment]
Good idea, I now exported all new algorithms as `DSC_StreamKM`, `DSC_BICO_MOA` and `DSC_DStream_MOA` to the namespace. I also added the missing man pages for the latter two (inspired by our existing documentation in the stream package).

Usage is now as follows:

```R
stream = DSD_Gaussians(3,2)
algorithm = DSC_StreamKM(sizeCoreset = 1000, numClusters = 3, length=1000)
update(algorithm, stream, 1000)
plot(algorithm, stream, type="macro")

algorithm = DSC_BICO_MOA(Cluster=5, Dimensions = 2, MaxClusterFeatures = 1000, Projections = 10)
update(algorithm, stream, 1000)
plot(algorithm, stream, type="both")

stream = DSD_Gaussians(2,2, mu=rbind(c(-10,-10), c(10,10)))
algorithm = DSC_DStream_MOA(decayFactor = 0.998, Cm = 3, Cl = 0.8, Beta = 0.3)
update(algorithm, stream, 10000)
plot(algorithm, stream, type="macro")
```

Happy New Year!

**Comment by mhahsler** [comment]
Your changes are now merged. I did some cleanup and will release a new version of the package soon. Thanks for your help! -Michael

**Pull request merged**
